version: "3.8"
services:
  app:
    container_name: app
    build: ./flask
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./flask:/app

  db:
    container_name: db
    image: mysql:8-debian
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro

networks:
  default:
